//! Static historical ICC tournament data for Phase 1 seeding.
//!
//! All results are sourced from publicly available ICC records.
//! Columns: (team_slug, Stage)

use crate::scoring::{EventType, Stage};

// ─── Data structures ──────────────────────────────────────────────────────────

pub struct EventSeed {
    pub name: &'static str,
    pub short_name: &'static str,
    pub event_type: EventType,
    pub year: i32,
    pub host: &'static str,
    /// Vec of (team_slug, stage_reached)
    pub results: Vec<(&'static str, Stage)>,
}

// ─── Teams ────────────────────────────────────────────────────────────────────

/// Returns (slug, full_name, short_name, flag_emoji, country_code)
pub fn all_teams() -> Vec<(&'static str, &'static str, &'static str, &'static str, &'static str)> {
    vec![
        // ── Senior / multi-format nations ────────────────────────────────────
        ("india",         "India",           "IND", "🇮🇳", "IN"),
        ("australia",     "Australia",       "AUS", "🇦🇺", "AU"),
        ("england",       "England",         "ENG", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "GB"),
        ("pakistan",      "Pakistan",        "PAK", "🇵🇰", "PK"),
        ("west-indies",   "West Indies",     "WI",  "🏏",  ""),
        ("south-africa",  "South Africa",    "SA",  "🇿🇦", "ZA"),
        ("new-zealand",   "New Zealand",     "NZ",  "🇳🇿", "NZ"),
        ("sri-lanka",     "Sri Lanka",       "SL",  "🇱🇰", "LK"),
        ("bangladesh",    "Bangladesh",      "BAN", "🇧🇩", "BD"),
        ("zimbabwe",      "Zimbabwe",        "ZIM", "🇿🇼", "ZW"),
        ("afghanistan",   "Afghanistan",     "AFG", "🇦🇫", "AF"),
        ("ireland",       "Ireland",         "IRE", "🇮🇪", "IE"),
        ("netherlands",   "Netherlands",     "NED", "🇳🇱", "NL"),
        ("scotland",      "Scotland",        "SCO", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "GB"),
        ("kenya",         "Kenya",           "KEN", "🇰🇪", "KE"),
        ("namibia",       "Namibia",         "NAM", "🇳🇦", "NA"),
        ("nepal",         "Nepal",           "NEP", "🇳🇵", "NP"),
        ("oman",          "Oman",            "OMA", "🇴🇲", "OM"),
        ("uae",           "United Arab Emirates", "UAE", "🇦🇪", "AE"),
        ("usa",           "United States",   "USA", "🇺🇸", "US"),
        ("canada",        "Canada",          "CAN", "🇨🇦", "CA"),
        ("papua-new-guinea", "Papua New Guinea", "PNG", "🇵🇬", "PG"),
        ("bermuda",       "Bermuda",         "BER", "🇧🇲", "BM"),
        ("east-africa",   "East Africa",     "EA",  "🌍",  ""),
        ("uganda",        "Uganda",          "UGA", "🇺🇬", "UG"),
        ("trinidad-tobago","Trinidad & Tobago","TT","🇹🇹", "TT"),
        ("hong-kong",    "Hong Kong",       "HK",  "🇭🇰", "HK"),
        ("denmark",      "Denmark",         "DEN", "🇩🇰", "DK"),
        ("thailand",     "Thailand",        "THA", "🇹🇭", "TH"),
        ("nigeria",      "Nigeria",         "NIG", "🇳🇬", "NG"),
        ("indonesia",    "Indonesia",       "IDN", "🇮🇩", "ID"),
        ("rwanda",       "Rwanda",          "RWA", "🇷🇼", "RW"),
    ]
}

// ─── Events ───────────────────────────────────────────────────────────────────

pub fn all_events() -> Vec<EventSeed> {
    let mut events = Vec::new();

    events.extend(men_world_cup_events());
    events.extend(men_t20_world_cup_events());
    events.extend(men_knockout_champions_events());
    events.extend(world_test_championship_events());
    events.extend(women_world_cup_events());
    events.extend(women_t20_world_cup_events());
    events.extend(men_u19_world_cup_events());
    events.extend(women_u19_world_cup_events());

    events
}

// ──────────────────────────────────────────────────────────────────────────────
// Men's Cricket World Cup (multiplier 8)
// ──────────────────────────────────────────────────────────────────────────────

fn men_world_cup_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Men's Cricket World Cup 1975",
            short_name: "CWC 1975",
            event_type: EventType::MenWorldCup,
            year: 1975,
            host: "England",
            results: vec![
                ("west-indies",  Stage::Champion),
                ("australia",    Stage::Final),
                ("england",      Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("india",        Stage::FirstStage),
                ("pakistan",     Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("east-africa",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 1979",
            short_name: "CWC 1979",
            event_type: EventType::MenWorldCup,
            year: 1979,
            host: "England",
            results: vec![
                ("west-indies",  Stage::Champion),
                ("england",      Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("india",        Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("canada",       Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 1983",
            short_name: "CWC 1983",
            event_type: EventType::MenWorldCup,
            year: 1983,
            host: "England",
            results: vec![
                ("india",        Stage::Champion),
                ("west-indies",  Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("england",      Stage::SemiFinal),
                ("australia",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 1987",
            short_name: "CWC 1987",
            event_type: EventType::MenWorldCup,
            year: 1987,
            host: "India & Pakistan",
            results: vec![
                ("australia",    Stage::Champion),
                ("england",      Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("india",        Stage::SemiFinal),
                ("west-indies",  Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 1992",
            short_name: "CWC 1992",
            event_type: EventType::MenWorldCup,
            year: 1992,
            host: "Australia & New Zealand",
            results: vec![
                ("pakistan",     Stage::Champion),
                ("england",      Stage::Final),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::SemiFinal),
                ("australia",    Stage::FirstStage),
                ("india",        Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 1996",
            short_name: "CWC 1996",
            event_type: EventType::MenWorldCup,
            year: 1996,
            host: "India, Pakistan & Sri Lanka",
            results: vec![
                ("sri-lanka",    Stage::Champion),
                ("australia",    Stage::Final),
                ("india",        Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("pakistan",     Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("zimbabwe",     Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
                ("uae",          Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 1999",
            short_name: "CWC 1999",
            event_type: EventType::MenWorldCup,
            year: 1999,
            host: "England",
            results: vec![
                ("australia",    Stage::Champion),
                ("pakistan",     Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("india",        Stage::OtherStage),
                ("zimbabwe",     Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("sri-lanka",    Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 2003",
            short_name: "CWC 2003",
            event_type: EventType::MenWorldCup,
            year: 2003,
            host: "South Africa, Zimbabwe & Kenya",
            results: vec![
                ("australia",    Stage::Champion),
                ("india",        Stage::Final),
                ("kenya",        Stage::SemiFinal),
                ("sri-lanka",    Stage::SemiFinal),
                ("pakistan",     Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("zimbabwe",     Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("west-indies",  Stage::FirstStage),
                ("south-africa", Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("canada",       Stage::FirstStage),
                ("namibia",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 2007",
            short_name: "CWC 2007",
            event_type: EventType::MenWorldCup,
            year: 2007,
            host: "West Indies",
            results: vec![
                ("australia",    Stage::Champion),
                ("sri-lanka",    Stage::Final),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::SemiFinal),
                ("england",      Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("ireland",      Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("india",        Stage::FirstStage),
                ("pakistan",     Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
                ("canada",       Stage::FirstStage),
                ("bermuda",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 2011",
            short_name: "CWC 2011",
            event_type: EventType::MenWorldCup,
            year: 2011,
            host: "India, Sri Lanka & Bangladesh",
            results: vec![
                ("india",        Stage::Champion),
                ("sri-lanka",    Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("england",      Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("australia",    Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("canada",       Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 2015",
            short_name: "CWC 2015",
            event_type: EventType::MenWorldCup,
            year: 2015,
            host: "Australia & New Zealand",
            results: vec![
                ("australia",    Stage::Champion),
                ("new-zealand",  Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("india",        Stage::SemiFinal),
                ("sri-lanka",    Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("west-indies",  Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("uae",          Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 2019",
            short_name: "CWC 2019",
            event_type: EventType::MenWorldCup,
            year: 2019,
            host: "England & Wales",
            results: vec![
                ("england",      Stage::Champion),
                ("new-zealand",  Stage::Final),
                ("india",        Stage::SemiFinal),
                ("australia",    Stage::SemiFinal),
                ("pakistan",     Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
                ("south-africa", Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's Cricket World Cup 2023",
            short_name: "CWC 2023",
            event_type: EventType::MenWorldCup,
            year: 2023,
            host: "India",
            results: vec![
                ("australia",    Stage::Champion),
                ("india",        Stage::Final),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::SemiFinal),
                ("pakistan",     Stage::FirstStage),
                ("england",      Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// Men's T20 World Cup (multiplier 6)
// ──────────────────────────────────────────────────────────────────────────────

fn men_t20_world_cup_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Men's T20 World Cup 2007",
            short_name: "T20 WC 2007",
            event_type: EventType::MenT20WorldCup,
            year: 2007,
            host: "South Africa",
            results: vec![
                ("india",        Stage::Champion),
                ("pakistan",     Stage::Final),
                ("australia",    Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("west-indies",  Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2009",
            short_name: "T20 WC 2009",
            event_type: EventType::MenT20WorldCup,
            year: 2009,
            host: "England",
            results: vec![
                ("pakistan",     Stage::Champion),
                ("sri-lanka",    Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("india",        Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("australia",    Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2010",
            short_name: "T20 WC 2010",
            event_type: EventType::MenT20WorldCup,
            year: 2010,
            host: "West Indies",
            results: vec![
                ("england",      Stage::Champion),
                ("australia",    Stage::Final),
                ("west-indies",  Stage::SemiFinal),
                ("pakistan",     Stage::SemiFinal),
                ("india",        Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("sri-lanka",    Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2012",
            short_name: "T20 WC 2012",
            event_type: EventType::MenT20WorldCup,
            year: 2012,
            host: "Sri Lanka",
            results: vec![
                ("west-indies",  Stage::Champion),
                ("sri-lanka",    Stage::Final),
                ("australia",    Stage::SemiFinal),
                ("pakistan",     Stage::SemiFinal),
                ("india",        Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2014",
            short_name: "T20 WC 2014",
            event_type: EventType::MenT20WorldCup,
            year: 2014,
            host: "Bangladesh",
            results: vec![
                ("sri-lanka",    Stage::Champion),
                ("india",        Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
                ("nepal",        Stage::FirstStage),
                ("uae",          Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("hong-kong",    Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2016",
            short_name: "T20 WC 2016",
            event_type: EventType::MenT20WorldCup,
            year: 2016,
            host: "India",
            results: vec![
                ("west-indies",  Stage::Champion),
                ("england",      Stage::Final),
                ("india",        Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("sri-lanka",    Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("oman",         Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("uae",          Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2021",
            short_name: "T20 WC 2021",
            event_type: EventType::MenT20WorldCup,
            year: 2021,
            host: "UAE & Oman",
            results: vec![
                ("australia",    Stage::Champion),
                ("new-zealand",  Stage::Final),
                ("england",      Stage::SemiFinal),
                ("pakistan",     Stage::SemiFinal),
                ("india",        Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("sri-lanka",    Stage::OtherStage),
                ("afghanistan",  Stage::OtherStage),
                ("namibia",      Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("oman",         Stage::FirstStage),
                ("papua-new-guinea", Stage::FirstStage),
                ("uae",          Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2022",
            short_name: "T20 WC 2022",
            event_type: EventType::MenT20WorldCup,
            year: 2022,
            host: "Australia",
            results: vec![
                ("england",      Stage::Champion),
                ("pakistan",     Stage::Final),
                ("india",        Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("sri-lanka",    Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("australia",    Stage::OtherStage),
                ("afghanistan",  Stage::OtherStage),
                ("zimbabwe",     Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("namibia",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("uae",          Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's T20 World Cup 2024",
            short_name: "T20 WC 2024",
            event_type: EventType::MenT20WorldCup,
            year: 2024,
            host: "USA & West Indies",
            results: vec![
                ("india",        Stage::Champion),
                ("south-africa", Stage::Final),
                ("afghanistan",  Stage::SemiFinal),
                ("england",      Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("netherlands",  Stage::FirstStage),
                ("canada",       Stage::FirstStage),
                ("oman",         Stage::FirstStage),
                ("usa",          Stage::FirstStage),
                ("namibia",      Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("nepal",        Stage::FirstStage),
                ("uganda",       Stage::FirstStage),
                ("papua-new-guinea", Stage::FirstStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// Men's Knockout / Champions Trophy (multiplier 5)
// ──────────────────────────────────────────────────────────────────────────────

fn men_knockout_champions_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Wills International Cup 1998",
            short_name: "KO 1998",
            event_type: EventType::MenKnockoutChampions,
            year: 1998,
            host: "Bangladesh",
            results: vec![
                ("south-africa", Stage::Champion),
                ("west-indies",  Stage::Final),
                ("india",        Stage::SemiFinal),
                ("zimbabwe",     Stage::SemiFinal),
                ("england",      Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("australia",    Stage::OtherStage),
                ("kenya",        Stage::OtherStage),
                ("sri-lanka",    Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Knockout Trophy 2000",
            short_name: "KO 2000",
            event_type: EventType::MenKnockoutChampions,
            year: 2000,
            host: "Kenya",
            results: vec![
                ("new-zealand",  Stage::Champion),
                ("india",        Stage::Final),
                ("australia",    Stage::SemiFinal),
                ("pakistan",     Stage::SemiFinal),
                ("england",      Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("sri-lanka",    Stage::OtherStage),
                ("zimbabwe",     Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
                ("south-africa", Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2002",
            short_name: "CT 2002",
            event_type: EventType::MenKnockoutChampions,
            year: 2002,
            host: "Sri Lanka",
            results: vec![
                // Shared title – India and Sri Lanka both awarded Champion points
                ("india",        Stage::Champion),
                ("sri-lanka",    Stage::Champion),
                ("south-africa", Stage::SemiFinal),
                ("zimbabwe",     Stage::SemiFinal),
                ("england",      Stage::FirstStage),
                ("pakistan",     Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("australia",    Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2004",
            short_name: "CT 2004",
            event_type: EventType::MenKnockoutChampions,
            year: 2004,
            host: "England",
            results: vec![
                ("west-indies",  Stage::Champion),
                ("england",      Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("sri-lanka",    Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("india",        Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("zimbabwe",     Stage::OtherStage),
                ("new-zealand",  Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("kenya",        Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2006",
            short_name: "CT 2006",
            event_type: EventType::MenKnockoutChampions,
            year: 2006,
            host: "India",
            results: vec![
                ("australia",    Stage::Champion),
                ("west-indies",  Stage::Final),
                ("india",        Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::FirstStage),
                ("pakistan",     Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("england",      Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2009",
            short_name: "CT 2009",
            event_type: EventType::MenKnockoutChampions,
            year: 2009,
            host: "South Africa",
            results: vec![
                ("australia",    Stage::Champion),
                ("new-zealand",  Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("england",      Stage::SemiFinal),
                ("india",        Stage::FirstStage),
                ("pakistan",     Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2013",
            short_name: "CT 2013",
            event_type: EventType::MenKnockoutChampions,
            year: 2013,
            host: "England & Wales",
            results: vec![
                ("india",        Stage::Champion),
                ("england",      Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("sri-lanka",    Stage::SemiFinal),
                ("south-africa", Stage::FirstStage),
                ("australia",    Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2017",
            short_name: "CT 2017",
            event_type: EventType::MenKnockoutChampions,
            year: 2017,
            host: "England & Wales",
            results: vec![
                ("pakistan",     Stage::Champion),
                ("india",        Stage::Final),
                ("bangladesh",   Stage::SemiFinal),
                ("england",      Stage::SemiFinal),
                ("south-africa", Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("australia",    Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Champions Trophy 2025",
            short_name: "CT 2025",
            event_type: EventType::MenKnockoutChampions,
            year: 2025,
            host: "Pakistan & UAE",
            results: vec![
                ("india",        Stage::Champion),
                ("new-zealand",  Stage::Final),
                ("australia",    Stage::SemiFinal),
                ("south-africa", Stage::SemiFinal),
                ("pakistan",     Stage::FirstStage),
                ("bangladesh",   Stage::FirstStage),
                ("england",      Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// World Test Championship (multiplier 7)
// ──────────────────────────────────────────────────────────────────────────────

fn world_test_championship_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC World Test Championship 2019–21",
            short_name: "WTC 2021",
            event_type: EventType::TestChampionship,
            year: 2021,
            host: "Various / England (Final)",
            results: vec![
                ("new-zealand",  Stage::Champion),
                ("india",        Stage::Final),
                ("australia",    Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("sri-lanka",    Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
            ],
        },
        EventSeed {
            name: "ICC World Test Championship 2021–23",
            short_name: "WTC 2023",
            event_type: EventType::TestChampionship,
            year: 2023,
            host: "Various / England (Final)",
            results: vec![
                ("australia",    Stage::Champion),
                ("india",        Stage::Final),
                ("england",      Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("sri-lanka",    Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("zimbabwe",     Stage::OtherStage),
            ],
        },
        EventSeed {
            name: "ICC World Test Championship 2023–25",
            short_name: "WTC 2025",
            event_type: EventType::TestChampionship,
            year: 2025,
            host: "Various / England (Final)",
            results: vec![
                ("south-africa", Stage::Champion),
                ("australia",    Stage::Final),
                ("india",        Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("sri-lanka",    Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("zimbabwe",     Stage::OtherStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// Women's World Cup (multiplier 4)
// ──────────────────────────────────────────────────────────────────────────────

fn women_world_cup_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Women's World Cup 1973",
            short_name: "WWC 1973",
            event_type: EventType::WomenWorldCup,
            year: 1973,
            host: "England",
            results: vec![
                ("england",       Stage::Champion),
                ("australia",     Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("trinidad-tobago", Stage::SemiFinal),
                ("india",         Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 1978",
            short_name: "WWC 1978",
            event_type: EventType::WomenWorldCup,
            year: 1978,
            host: "India",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("trinidad-tobago", Stage::SemiFinal),
                ("india",         Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 1982",
            short_name: "WWC 1982",
            event_type: EventType::WomenWorldCup,
            year: 1982,
            host: "New Zealand",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("trinidad-tobago", Stage::SemiFinal),
                ("india",         Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 1988",
            short_name: "WWC 1988",
            event_type: EventType::WomenWorldCup,
            year: 1988,
            host: "Australia",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("netherlands",   Stage::SemiFinal),
                ("india",         Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 1993",
            short_name: "WWC 1993",
            event_type: EventType::WomenWorldCup,
            year: 1993,
            host: "England",
            results: vec![
                ("england",       Stage::Champion),
                ("new-zealand",   Stage::Final),
                ("australia",     Stage::SemiFinal),
                ("india",         Stage::SemiFinal),
                ("west-indies",   Stage::FirstStage),
                ("denmark",       Stage::FirstStage),
                ("netherlands",   Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 1997",
            short_name: "WWC 1997",
            event_type: EventType::WomenWorldCup,
            year: 1997,
            host: "India",
            results: vec![
                ("australia",     Stage::Champion),
                ("south-africa",  Stage::Final),
                ("india",         Stage::SemiFinal),
                ("new-zealand",   Stage::SemiFinal),
                ("england",       Stage::FirstStage),
                ("west-indies",   Stage::FirstStage),
                ("ireland",       Stage::FirstStage),
                ("netherlands",   Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 2000",
            short_name: "WWC 2000",
            event_type: EventType::WomenWorldCup,
            year: 2000,
            host: "New Zealand",
            results: vec![
                ("new-zealand",   Stage::Champion),
                ("australia",     Stage::Final),
                ("india",         Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("england",       Stage::FirstStage),
                ("west-indies",   Stage::FirstStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 2005",
            short_name: "WWC 2005",
            event_type: EventType::WomenWorldCup,
            year: 2005,
            host: "South Africa",
            results: vec![
                ("australia",     Stage::Champion),
                ("india",         Stage::Final),
                ("england",       Stage::SemiFinal),
                ("new-zealand",   Stage::SemiFinal),
                ("south-africa",  Stage::FirstStage),
                ("west-indies",   Stage::FirstStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 2009",
            short_name: "WWC 2009",
            event_type: EventType::WomenWorldCup,
            year: 2009,
            host: "Australia",
            results: vec![
                ("england",       Stage::Champion),
                ("new-zealand",   Stage::Final),
                ("australia",     Stage::SemiFinal),
                ("india",         Stage::SemiFinal),
                ("south-africa",  Stage::FirstStage),
                ("west-indies",   Stage::FirstStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
                ("pakistan",      Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 2013",
            short_name: "WWC 2013",
            event_type: EventType::WomenWorldCup,
            year: 2013,
            host: "India",
            results: vec![
                ("australia",     Stage::Champion),
                ("west-indies",   Stage::Final),
                ("england",       Stage::SemiFinal),
                ("sri-lanka",     Stage::SemiFinal),
                ("south-africa",  Stage::OtherStage),
                ("india",         Stage::OtherStage),
                ("new-zealand",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::FirstStage),
                ("ireland",       Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's World Cup 2017",
            short_name: "WWC 2017",
            event_type: EventType::WomenWorldCup,
            year: 2017,
            host: "England & Wales",
            results: vec![
                ("england",       Stage::Champion),
                ("india",         Stage::Final),
                ("australia",     Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("new-zealand",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("sri-lanka",     Stage::OtherStage),
                ("west-indies",   Stage::OtherStage),
            ],
        },
        EventSeed {
            name: "ICC Women's Cricket World Cup 2022",
            short_name: "WWC 2022",
            event_type: EventType::WomenWorldCup,
            year: 2022,
            host: "New Zealand",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("west-indies",   Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("india",         Stage::OtherStage),
                ("new-zealand",   Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// Women's T20 World Cup (multiplier 3)
// ──────────────────────────────────────────────────────────────────────────────

fn women_t20_world_cup_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Women's T20 World Cup 2009",
            short_name: "WT20 WC 2009",
            event_type: EventType::WomenT20WorldCup,
            year: 2009,
            host: "England",
            results: vec![
                ("england",       Stage::Champion),
                ("new-zealand",   Stage::Final),
                ("south-africa",  Stage::SemiFinal),
                ("india",         Stage::SemiFinal),
                ("australia",     Stage::FirstStage),
                ("west-indies",   Stage::FirstStage),
                ("pakistan",      Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2010",
            short_name: "WT20 WC 2010",
            event_type: EventType::WomenT20WorldCup,
            year: 2010,
            host: "West Indies",
            results: vec![
                ("australia",     Stage::Champion),
                ("west-indies",   Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("england",       Stage::FirstStage),
                ("india",         Stage::FirstStage),
                ("pakistan",      Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2012",
            short_name: "WT20 WC 2012",
            event_type: EventType::WomenT20WorldCup,
            year: 2012,
            host: "Sri Lanka",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("west-indies",   Stage::SemiFinal),
                ("south-africa",  Stage::FirstStage),
                ("india",         Stage::FirstStage),
                ("pakistan",      Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
                ("bangladesh",    Stage::FirstStage),
                ("ireland",       Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2014",
            short_name: "WT20 WC 2014",
            event_type: EventType::WomenT20WorldCup,
            year: 2014,
            host: "Bangladesh",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("new-zealand",   Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("india",         Stage::OtherStage),
                ("west-indies",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2016",
            short_name: "WT20 WC 2016",
            event_type: EventType::WomenT20WorldCup,
            year: 2016,
            host: "India",
            results: vec![
                ("west-indies",   Stage::Champion),
                ("australia",     Stage::Final),
                ("england",       Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("india",         Stage::OtherStage),
                ("new-zealand",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2018",
            short_name: "WT20 WC 2018",
            event_type: EventType::WomenT20WorldCup,
            year: 2018,
            host: "West Indies",
            results: vec![
                ("australia",     Stage::Champion),
                ("england",       Stage::Final),
                ("india",         Stage::SemiFinal),
                ("west-indies",   Stage::SemiFinal),
                ("south-africa",  Stage::OtherStage),
                ("new-zealand",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2020",
            short_name: "WT20 WC 2020",
            event_type: EventType::WomenT20WorldCup,
            year: 2020,
            host: "Australia",
            results: vec![
                ("australia",     Stage::Champion),
                ("india",         Stage::Final),
                ("england",       Stage::SemiFinal),
                ("south-africa",  Stage::SemiFinal),
                ("new-zealand",   Stage::OtherStage),
                ("west-indies",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
                ("thailand",      Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2023",
            short_name: "WT20 WC 2023",
            event_type: EventType::WomenT20WorldCup,
            year: 2023,
            host: "South Africa",
            results: vec![
                ("australia",     Stage::Champion),
                ("south-africa",  Stage::Final),
                ("india",         Stage::SemiFinal),
                ("england",       Stage::SemiFinal),
                ("new-zealand",   Stage::OtherStage),
                ("west-indies",   Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's T20 World Cup 2024",
            short_name: "WT20 WC 2024",
            event_type: EventType::WomenT20WorldCup,
            year: 2024,
            host: "UAE",
            results: vec![
                ("new-zealand",   Stage::Champion),
                ("south-africa",  Stage::Final),
                ("australia",     Stage::SemiFinal),
                ("west-indies",   Stage::SemiFinal),
                ("india",         Stage::OtherStage),
                ("england",       Stage::OtherStage),
                ("pakistan",      Stage::OtherStage),
                ("bangladesh",    Stage::OtherStage),
                ("ireland",       Stage::FirstStage),
                ("sri-lanka",     Stage::FirstStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// Men's U19 World Cup (multiplier 2)
// ──────────────────────────────────────────────────────────────────────────────

fn men_u19_world_cup_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Men's U19 World Cup 1988",
            short_name: "U19 CWC 1988",
            event_type: EventType::MenU19,
            year: 1988,
            host: "Australia",
            results: vec![
                ("australia",    Stage::Champion),
                ("pakistan",     Stage::Final),
                ("england",      Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("india",        Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 1998",
            short_name: "U19 CWC 1998",
            event_type: EventType::MenU19,
            year: 1998,
            host: "South Africa",
            results: vec![
                ("england",      Stage::Champion),
                ("new-zealand",  Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("south-africa", Stage::SemiFinal),
                ("india",        Stage::FirstStage),
                ("australia",    Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2000",
            short_name: "U19 CWC 2000",
            event_type: EventType::MenU19,
            year: 2000,
            host: "Sri Lanka",
            results: vec![
                ("india",        Stage::Champion),
                ("sri-lanka",    Stage::Final),
                ("new-zealand",  Stage::SemiFinal),
                ("australia",    Stage::SemiFinal),
                ("pakistan",     Stage::FirstStage),
                ("south-africa", Stage::FirstStage),
                ("england",      Stage::FirstStage),
                ("west-indies",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2002",
            short_name: "U19 CWC 2002",
            event_type: EventType::MenU19,
            year: 2002,
            host: "New Zealand",
            results: vec![
                ("australia",    Stage::Champion),
                ("south-africa", Stage::Final),
                ("england",      Stage::SemiFinal),
                ("zimbabwe",     Stage::SemiFinal),
                ("india",        Stage::FirstStage),
                ("pakistan",     Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2004",
            short_name: "U19 CWC 2004",
            event_type: EventType::MenU19,
            year: 2004,
            host: "Bangladesh",
            results: vec![
                ("pakistan",     Stage::Champion),
                ("west-indies",  Stage::Final),
                ("india",        Stage::SemiFinal),
                ("bangladesh",   Stage::SemiFinal),
                ("australia",    Stage::FirstStage),
                ("south-africa", Stage::FirstStage),
                ("england",      Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2006",
            short_name: "U19 CWC 2006",
            event_type: EventType::MenU19,
            year: 2006,
            host: "Sri Lanka",
            results: vec![
                ("pakistan",     Stage::Champion),
                ("india",        Stage::Final),
                ("west-indies",  Stage::SemiFinal),
                ("england",      Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("new-zealand",  Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2008",
            short_name: "U19 CWC 2008",
            event_type: EventType::MenU19,
            year: 2008,
            host: "Malaysia",
            results: vec![
                ("india",        Stage::Champion),
                ("south-africa", Stage::Final),
                ("england",      Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("afghanistan",  Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2010",
            short_name: "U19 CWC 2010",
            event_type: EventType::MenU19,
            year: 2010,
            host: "New Zealand",
            results: vec![
                ("australia",    Stage::Champion),
                ("pakistan",     Stage::Final),
                ("india",        Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("south-africa", Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("afghanistan",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2012",
            short_name: "U19 CWC 2012",
            event_type: EventType::MenU19,
            year: 2012,
            host: "Australia",
            results: vec![
                ("australia",    Stage::Champion),
                ("india",        Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("pakistan",     Stage::SemiFinal),
                ("england",      Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("afghanistan",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("canada",       Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2014",
            short_name: "U19 CWC 2014",
            event_type: EventType::MenU19,
            year: 2014,
            host: "UAE",
            results: vec![
                ("south-africa", Stage::Champion),
                ("pakistan",     Stage::Final),
                ("england",      Stage::SemiFinal),
                ("afghanistan",  Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("india",        Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("nepal",        Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2016",
            short_name: "U19 CWC 2016",
            event_type: EventType::MenU19,
            year: 2016,
            host: "Bangladesh",
            results: vec![
                ("west-indies",  Stage::Champion),
                ("india",        Stage::Final),
                ("nepal",        Stage::SemiFinal),
                ("bangladesh",   Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("new-zealand",  Stage::FirstStage),
                ("afghanistan",  Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2018",
            short_name: "U19 CWC 2018",
            event_type: EventType::MenU19,
            year: 2018,
            host: "New Zealand",
            results: vec![
                ("india",        Stage::Champion),
                ("australia",    Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("afghanistan",  Stage::SemiFinal),
                ("england",      Stage::OtherStage),
                ("south-africa", Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("namibia",      Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2020",
            short_name: "U19 CWC 2020",
            event_type: EventType::MenU19,
            year: 2020,
            host: "South Africa",
            results: vec![
                ("bangladesh",   Stage::Champion),
                ("india",        Stage::Final),
                ("pakistan",     Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("australia",    Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("afghanistan",  Stage::OtherStage),
                ("south-africa", Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("nigeria",      Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2022",
            short_name: "U19 CWC 2022",
            event_type: EventType::MenU19,
            year: 2022,
            host: "West Indies",
            results: vec![
                ("india",        Stage::Champion),
                ("england",      Stage::Final),
                ("afghanistan",  Stage::SemiFinal),
                ("australia",    Stage::SemiFinal),
                ("south-africa", Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("nepal",        Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Men's U19 World Cup 2024",
            short_name: "U19 CWC 2024",
            event_type: EventType::MenU19,
            year: 2024,
            host: "South Africa",
            results: vec![
                ("australia",    Stage::Champion),
                ("india",        Stage::Final),
                ("south-africa", Stage::SemiFinal),
                ("west-indies",  Stage::SemiFinal),
                ("pakistan",     Stage::OtherStage),
                ("england",      Stage::OtherStage),
                ("new-zealand",  Stage::OtherStage),
                ("afghanistan",  Stage::OtherStage),
                ("bangladesh",   Stage::FirstStage),
                ("ireland",      Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
            ],
        },
    ]
}

// ──────────────────────────────────────────────────────────────────────────────
// Women's U19 World Cup (multiplier 1)
// ──────────────────────────────────────────────────────────────────────────────

fn women_u19_world_cup_events() -> Vec<EventSeed> {
    vec![
        EventSeed {
            name: "ICC Women's U19 T20 World Cup 2023",
            short_name: "WU19 T20 WC 2023",
            event_type: EventType::WomenU19,
            year: 2023,
            host: "South Africa",
            results: vec![
                ("india",        Stage::Champion),
                ("england",      Stage::Final),
                ("australia",    Stage::SemiFinal),
                ("new-zealand",  Stage::SemiFinal),
                ("south-africa", Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("ireland",      Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("uae",          Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("scotland",     Stage::FirstStage),
                ("usa",          Stage::FirstStage),
                ("indonesia",    Stage::FirstStage),
                ("rwanda",       Stage::FirstStage),
            ],
        },
        EventSeed {
            name: "ICC Women's U19 T20 World Cup 2025",
            short_name: "WU19 T20 WC 2025",
            event_type: EventType::WomenU19,
            year: 2025,
            host: "Malaysia",
            results: vec![
                ("south-africa", Stage::Champion),
                ("england",      Stage::Final),
                ("australia",    Stage::SemiFinal),
                ("india",        Stage::SemiFinal),
                ("new-zealand",  Stage::OtherStage),
                ("west-indies",  Stage::OtherStage),
                ("pakistan",     Stage::OtherStage),
                ("bangladesh",   Stage::OtherStage),
                ("ireland",      Stage::FirstStage),
                ("sri-lanka",    Stage::FirstStage),
                ("zimbabwe",     Stage::FirstStage),
                ("uae",          Stage::FirstStage),
            ],
        },
    ]
}
